export const Routes = {
  welcome: '/',
  home: '/home',
  internetWarning: '/internet-warning',
  createWallet: '/create-wallet',
  restoreWallet: '/restore-wallet',
  createImportAccount: '/create-import-account',
  unlock: '/unlock',
  accountDetails: '/account-details',
  showPrivateKeys: '/show-private-keys',
  aboutUs: '/about-us',
  logoutWallet: '/logout-wallet',
  revealMnemonicPhrase: '/reveal-mnemonic-phrase',
  tokenDetails: '/token-details',
  receiveToken: '/receive-token',
  addAssets: '/add-assets',
  backUp: '/back-up',
};
