export const BG_WALLET_CREATE_WALLET = 'WALLET/CREATE_WALLET';
export const BG_WALLET_CREATE_ACCOUNT = 'WALLET/CREATE_ACCOUNT';
export const BG_WALLET_RESTORE_WALLET = 'WALLET/BG_WALLET_RESTORE_WALLET';
export const BG_WALLET_RESET_STATE = 'WALLET/BG_WALLET_RESET_STATE';
export const BG_WALLET_GET_BALANCE = 'WALLET/GET_BALANCE';
export const BG_WALLET_GET_TOKEN_PRICE = 'WALLET/GET_TOKEN_PRICE';
export const BG_WALLET_GET_ACCOUNT_LIST = 'WALLET/GET_ACCOUNT_LIST';
export const BG_WALLET_UNLOCK_WALLET = 'WALLET/BG_WALLET_UNLOCK_WALLET';
export const BG_WALLET_LOCK_WALLET = 'WALLET/BG_WALLET_LOCK_WALLET';
export const BG_WALLET_LOGOUT_WALLET = 'WALLET/BG_WALLET_LOGOUT_WALLET';
export const BG_WALLET_SHOW_SEED_PHARES = 'WALLET/BG_WALLET_SHOW_SEED_PHARES';
export const BG_WALLET_BACK_UP_WALLET = 'WALLET/BG_WALLET_BACK_UP_WALLET';
export const BG_WALLET_TRANSFER_TOKEN = 'WALLET/BG_WALLET_TRANSFER_TOKEN';
export const BG_WALLET_CHECK_IS_VALID_ADDRESS =
  'WALLET/BG_WALLET_CHECK_IS_VALID_ADDRESS';
export const BG_WALLET_CREATE_WALLET_COMPLETED =
  'WALLET/BG_WALLET_CREATE_WALLET_COMPLETED';
export const BG_WALLET_CHECK_IS_VALID_SEED_PHRASE =
  'WALLET/BG_WALLET_CHECK_IS_VALID_SEED_PHRASE';

// Account
export const BG_ACCOUNT_ADD_ACCOUNT = 'ACCOUNT/ADD_ACCOUNT';
export const BG_WALLET_UPDATE_ACCOUNT = 'WALLET/UPDATE_ACCOUNT';
export const BG_ACCOUNT_CHANGE_ACCOUNT = 'ACCOUNT/CHANGE_ACCOUNT';
export const BG_ACCOUNT_IMPORT_ACCOUNT = 'ACCOUNT/IMPORT_ACCOUNT';
export const BG_ACCOUNT_SHOW_PRIVATE_KEYS = 'ACCOUNT/SHOW_PRIVATE_KEYS';
export const BG_ACCOUNT_CHANGE_ACCOUNT_NAME = 'ACCOUNT/CHANGE_ACCOUNT_NAME';

// Transactions
export const BG_TRANSACTION_GET_TX_LIST =
  'TRANSACTION/BG_TRANSACTION_GET_TX_LIST';

// Settings
export const BG_SETTINGS_SET_AUTO_LOCK_TIMER = 'SETTINGS/SET_AUTO_LOCK_TIMER';

export default {
  BG_WALLET_CREATE_ACCOUNT,
  BG_WALLET_CREATE_WALLET,
  BG_WALLET_UPDATE_ACCOUNT,
  BG_WALLET_GET_BALANCE,
  BG_WALLET_GET_TOKEN_PRICE,
  BG_WALLET_GET_ACCOUNT_LIST,
  BG_WALLET_UNLOCK_WALLET,
  BG_WALLET_LOCK_WALLET,
  BG_WALLET_CREATE_WALLET_COMPLETED,
  BG_WALLET_CHECK_IS_VALID_SEED_PHRASE,
  BG_WALLET_CHECK_IS_VALID_ADDRESS,
  BG_WALLET_RESTORE_WALLET,
  BG_WALLET_LOGOUT_WALLET,
  BG_WALLET_SHOW_SEED_PHARES,
  BG_WALLET_BACK_UP_WALLET,
  BG_WALLET_TRANSFER_TOKEN,
  BG_WALLET_RESET_STATE,

  BG_ACCOUNT_ADD_ACCOUNT,
  BG_ACCOUNT_CHANGE_ACCOUNT,
  BG_ACCOUNT_IMPORT_ACCOUNT,
  BG_ACCOUNT_SHOW_PRIVATE_KEYS,
  BG_ACCOUNT_CHANGE_ACCOUNT_NAME,

  BG_TRANSACTION_GET_TX_LIST,

  BG_SETTINGS_SET_AUTO_LOCK_TIMER,
};
