export const BG_WALLET_CREATE_SEED_WORDS = 'WALLET/CREATE_SEED_WORDS';
export const BG_WALLET_CREATE_WALLET = 'WALLET/CREATE_WALLET';
export const BG_WALLET_CREATE_ACCOUNT = 'WALLET/CREATE_ACCOUNT';
export const BG_WALLET_UPDATE_ACCOUNT = 'WALLET/UPDATE_ACCOUNT';
export const BG_WALLET_GET_BALANCE = 'WALLET/GET_BALANCE';
export const BG_WALLET_GET_ACCOUNT_LIST = 'WALLET/GET_ACCOUNT_LIST';

export default {
  BG_WALLET_CREATE_SEED_WORDS,
  BG_WALLET_CREATE_ACCOUNT,
  BG_WALLET_CREATE_WALLET,
  BG_WALLET_UPDATE_ACCOUNT,
  BG_WALLET_GET_BALANCE,
  BG_WALLET_GET_ACCOUNT_LIST,
};
